"""rename adress

Revision ID: 48b1e635488c
Revises: db3d8265f739
Create Date: 2025-01-15 12:17:41.000082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b1e635488c'
down_revision = 'db3d8265f739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('department', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('department', 'location',  new_column_name='address')
    # ### end Alembic commands ###
